In [126]:
import py_entitymatching as em

A = em.read_csv_metadata('/Users/yashtrivedi/cs839ps3/A.csv')
A['ID'] = range(0, len(A))
em.set_key(A, 'ID')

B = em.read_csv_metadata('/Users/yashtrivedi/cs839ps3/B.csv')
B['ID'] = range(0, len(B))
em.set_key(B, 'ID')

#print len(A), len(B)
#print A.columns.values
#print B.columns.values

ab = em.AttrEquivalenceBlocker()
C1 = ab.block_tables(A, B, 'club', 'club', 
                     l_output_attrs=['full name', 'club', 'overall'], 
                     r_output_attrs=['full_name', 'club', 'overall'], 
                     n_jobs=-1)

ob = em.OverlapBlocker()
C2 = ob.block_tables(A, B, 'club', 'club', word_level=False,
                     q_val = 3, overlap_size = 2,
                     l_output_attrs=['full name', 'club', 'overall'], 
                     r_output_attrs=['full_name', 'club', 'overall'], 
                     n_jobs=-1)

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:04

In [127]:
print len(C1)
print len(C2)

83686
1683092

In [128]:
dbg = em.debug_blocker(C2, A, B, output_size=200)
dbg.head()

,_id,ltable_ID,rtable_ID,ltable_name,ltable_club,ltable_nation,ltable_league,rtable_name,rtable_club,rtable_nation,rtable_league
0,0,1598,747,aythami artiles,ud las palmas,spain,laliga 1 i 2 i 3,aythami artiles,cordoba cf,spain,laliga 1 i 2 i 3
1,1,3539,1764,alex,salerno,portugal,calcio b,alex,vercelli,portugal,calcio b
2,2,2201,8733,jaime romero,cordoba cf,spain,laliga 1 i 2 i 3,jaime romero,cd lugo,spain,laliga 1 i 2 i 3
3,3,2347,8742,filipe augusto,sl benfica,brazil,super lig,filipe augusto,alanyaspor,brazil,super lig
4,4,1925,967,salvador agra,vila das aves,portugal,laliga 1 i 2 i 3,salvador agra,granada cf,portugal,laliga 1 i 2 i 3

In [138]:
ob = em.OverlapBlocker()
D = ob.block_candset(C2, 'name', 'name', word_level=False, q_val=2, overlap_size=2, n_jobs=-1)

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:16

In [139]:
print len(D)
D

205665

,_id,ltable_ID,rtable_ID,ltable_full name,ltable_club,ltable_overall,rtable_full_name,rtable_club,rtable_overall
0,0,0,0,c. ronaldo dos santos aveiro,real madrid,94,c. ronaldo dos santos aveiro,real madrid cf,94
9,9,2537,0,goncalo manuel ganchinho guedes,valencia cf,74,c. ronaldo dos santos aveiro,real madrid cf,94
13,13,75,0,francisco roman alarcon suarez,real madrid,86,c. ronaldo dos santos aveiro,real madrid cf,94
14,14,78,0,diego da silva costa,atletico madrid,86,c. ronaldo dos santos aveiro,real madrid cf,94
16,16,84,0,carlos henrique venancio casimiro,real madrid,86,c. ronaldo dos santos aveiro,real madrid cf,94
17,17,2062,0,theo hernandez,real madrid,75,c. ronaldo dos santos aveiro,real madrid cf,94
19,19,101,0,carlos henrique venancio casimiro,real madrid,85,c. ronaldo dos santos aveiro,real madrid cf,94
23,23,125,0,bruno soriano llido,villarreal cf,84,c. ronaldo dos santos aveiro,real madrid cf,94
26,26,141,0,marco asensio willemsen,real madrid,84,c. ronaldo dos santos aveiro,real madrid cf,94
31,31,177,0,kevin gameiro,atletico madrid,83,c. ronaldo dos santos aveiro,real madrid cf,94
33,33,31,0,antoine griezmann,atletico madrid,88,c. ronaldo dos santos aveiro,real madrid cf,94
34,34,2121,0,salvador jose milhazes agra,granada cf,75,c. ronaldo dos santos aveiro,real madrid cf,94
43,43,2318,0,alejandro martinez sanchez,granada cf,74,c. ronaldo dos santos aveiro,real madrid cf,94
46,46,289,0,willian jose da silva,real sociedad,82,c. ronaldo dos santos aveiro,real madrid cf,94
47,47,2346,0,cristiano da silva,kashiwa reysol,74,c. ronaldo dos santos aveiro,real madrid cf,94
48,48,305,0,inigo martinez berridi,real sociedad,82,c. ronaldo dos santos aveiro,real madrid cf,94
50,50,309,0,manuel trigueros munoz,villarreal cf,82,c. ronaldo dos santos aveiro,real madrid cf,94
56,56,352,0,fernando jose torres sanz,atletico madrid,81,c. ronaldo dos santos aveiro,real madrid cf,94
59,59,2427,0,enes unal,villarreal cf,74,c. ronaldo dos santos aveiro,real madrid cf,94
62,62,391,0,mario gaspar perez martinez,villarreal cf,81,c. ronaldo dos santos aveiro,real madrid cf,94
63,63,1432,0,lucas hernandez,atletico madrid,76,c. ronaldo dos santos aveiro,real madrid cf,94
65,65,409,0,jose ignacio fernandez iglesias,real madrid,81,c. ronaldo dos santos aveiro,real madrid cf,94
66,66,2464,0,federico ricca,malaga cf,74,c. ronaldo dos santos aveiro,real madrid cf,94
69,69,2060,0,adalberto penaranda,malaga cf,75,c. ronaldo dos santos aveiro,real madrid cf,94
71,71,477,0,andres guardado,real betis,80,c. ronaldo dos santos aveiro,real madrid cf,94
73,73,487,0,ignacio piatti,impact montreal,80,c. ronaldo dos santos aveiro,real madrid cf,94
74,74,489,0,augusto fernandez,atletico madrid,80,c. ronaldo dos santos aveiro,real madrid cf,94
75,75,2547,0,enes unal,villarreal cf,74,c. ronaldo dos santos aveiro,real madrid cf,94
76,76,519,0,fabian orellana,valencia cf,80,c. ronaldo dos santos aveiro,real madrid cf,94
77,77,524,0,roberto soriano,villarreal cf,80,c. ronaldo dos santos aveiro,real madrid cf,94
...,...,...,...,...,...,...,...,...,...
210497,1682849,101,9723,carlos henrique venancio casimiro,real madrid,85,ambroise oyongo,montreal impact,71
210501,1682853,125,9723,bruno soriano llido,villarreal cf,84,ambroise oyongo,montreal impact,71
210504,1682856,141,9723,marco asensio willemsen,real madrid,84,ambroise oyongo,montreal impact,71
210520,1682872,274,9723,aaron ramsey,arsenal,82,ambroise oyongo,montreal impact,71
210523,1682875,289,9723,willian jose da silva,real sociedad,82,ambroise oyongo,montreal impact,71
210525,1682877,305,9723,inigo martinez berridi,real sociedad,82,ambroise oyongo,montreal impact,71
210548,1682900,404,9723,cedric bakambu,villarreal cf,81,ambroise oyongo,montreal impact,71
210558,1682910,2513,9723,tiago alves sales,al hilal,74,ambroise oyongo,montreal impact,71
210571,1682923,2592,9723,daniel congre,montpellier herault sc,74,ambroise oyongo,montreal impact,71
210575,1682927,2612,9723,taiseer al jassam,al ahli,74,ambroise oyongo,montreal impact,71
210578,1682930,568,9723,javier fuego martinez,villarreal cf,80,ambroise oyongo,montreal impact,71
210581,1682933,2624,9723,gorka elustondo urkola,atletico nacional,74,ambroise oyongo,montreal impact,71
210628,1682980,3038,9723,alfonso gonzalez,monterrey,73,ambroise oyongo,montreal impact,71
210640,1682992,1036,9723,jelle van damme,royal antwerp fc,77,ambroise oyongo,montreal impact,71
210642,1682994,3110,9723,jefferson cuero,monarcas morelia,73,ambroise oyongo,montreal impact,71
210650,1683002,3202,9723,tendai ndoro,al faisaly,73,ambroise oyongo,montreal impact,71
210652,1683004,1161,9723,sergio leon limones,real betis,77,ambroise oyongo,montreal impact,71
210654,1683006,1187,9723,alvaro gonzalez soberon,villarreal cf,77,ambroise oyongo,montreal impact,71
210655,1683007,1189,9723,terence kongolo,as monaco football club sa,77,ambroise oyongo,montreal impact,71
210665,1683017,1226,9723,marcos paulo mesquita lopes,as monaco football club sa,77,ambroise oyongo,montreal impact,71
210668,1683020,3287,9723,tendai ndoro,al faisaly,73,ambroise oyongo,montreal impact,71
210677,1683029,1314,9723,rodrigo hernandez cascante,villarreal cf,77,ambroise oyongo,montreal impact,71
210681,1683033,1350,9723,jerome roussillon,montpellier herault sc,76,ambroise oyongo,montreal impact,71
210691,1683043,3571,9723,bruno uvini bortolanca,al nassr,72,ambroise oyongo,montreal impact,71
210702,1683054,1586,9723,stephane sessegnon,montpellier herault sc,76,ambroise oyongo,montreal impact,71
210703,1683055,3635,9723,syam ben youssef,kasimpasa sk,72,ambroise oyongo,montreal impact,71
210709,1683061,3687,9723,abdul fatah aseri,al ahli,72,ambroise oyongo,montreal impact,71
210729,1683081,1866,9723,leonardo rodrigues pereira,al nassr,75,ambroise oyongo,montreal impact,71
210732,1683084,1936,9723,calum chambers,arsenal,75,ambroise oyongo,montreal impact,71
210735,1683087,1986,9723,leonel vangioni,monterrey,75,ambroise oyongo,montreal impact,71

In [140]:
dbg = em.debug_blocker(D, A, B, output_size=200)
dbg.head()

,_id,ltable_ID,rtable_ID,ltable_name,ltable_club,ltable_nation,ltable_league,rtable_name,rtable_club,rtable_nation,rtable_league
0,0,2702,9577,coloccini,san lorenzo de almagro,argentina,primera division,gonzalo rodríguez,san lorenzo de almagro,argentina,primera division
1,1,2702,8352,coloccini,san lorenzo de almagro,argentina,primera division,juan mercier,san lorenzo de almagro,argentina,primera division
2,2,2702,315,coloccini,san lorenzo de almagro,argentina,primera division,fernando belluschi,san lorenzo de almagro,argentina,primera division
3,3,2697,6662,braga,vila das aves,portugal,liga nos,pedró,vila das aves,portugal,liga nos
4,4,2697,4516,braga,vila das aves,portugal,liga nos,pedrinho,vila das aves,portugal,liga nos

In [141]:
S = em.sample_table(D, 450)

In [142]:
G = em.label_table(S, label_column_name='gold_labels')
G.to_csv('/Users/yashtrivedi/cs839ps3/G.csv', index=False)

In [145]:
train_test = em.split_train_test(G, train_proportion=0.7, random_state=0)
I = train_test['train']
J = train_test['test']

In [147]:
feature_table = em.get_features_for_matching(A, B)

The table shows the corresponding attributes along with their respective types.
Please confirm that the information  has been correctly inferred.
If you would like to skip this validation process in the future,
please set the flag validate_inferred_attr_types equal to false.

,Left Attribute,Right Attribute,Left Attribute Type,Right Attribute Type,Example Features
0,name,name,short string (1 word to 5 words),short string (1 word to 5 words),"Jaccard Similarity [3-grams, 3-grams]; Cosine Similarity [Space Delimiter, Space Delimiter]"
1,club,club,short string (1 word to 5 words),short string (1 word to 5 words),"Jaccard Similarity [3-grams, 3-grams]; Cosine Similarity [Space Delimiter, Space Delimiter]"
2,nation,nation,short string (1 word to 5 words),short string (1 word to 5 words),"Jaccard Similarity [3-grams, 3-grams]; Cosine Similarity [Space Delimiter, Space Delimiter]"
3,overall,overall,numeric,numeric,Exact Match; Absolute Norm
4,league,league,short string (1 word to 5 words),short string (1 word to 5 words),"Jaccard Similarity [3-grams, 3-grams]; Cosine Similarity [Space Delimiter, Space Delimiter]"
5,age,age,numeric,numeric,Exact Match; Absolute Norm
6,height,height,numeric,numeric,Exact Match; Absolute Norm
7,reactions,reactions,numeric,numeric,Exact Match; Absolute Norm
8,positioning,positioning,numeric,numeric,Exact Match; Absolute Norm
9,penalties,penalties,numeric,numeric,Exact Match; Absolute Norm
10,long passing,long passing,numeric,numeric,Exact Match; Absolute Norm
11,standing tackle,standing tackle,numeric,numeric,Exact Match; Absolute Norm
12,ball control,ball control,numeric,numeric,Exact Match; Absolute Norm
13,interceptions,interceptions,numeric,numeric,Exact Match; Absolute Norm
14,acceleration,acceleration,numeric,numeric,Exact Match; Absolute Norm
15,marking,marking,numeric,numeric,Exact Match; Absolute Norm
16,strength,strength,numeric,numeric,Exact Match; Absolute Norm
17,pac,pac,numeric,numeric,Exact Match; Absolute Norm
18,aggression,aggression,numeric,numeric,Exact Match; Absolute Norm
19,agility,agility,numeric,numeric,Exact Match; Absolute Norm
20,volleys,volleys,numeric,numeric,Exact Match; Absolute Norm
21,sprint speed,sprint speed,numeric,numeric,Exact Match; Absolute Norm
22,phy,phy,numeric,numeric,Exact Match; Absolute Norm
23,pas,pas,numeric,numeric,Exact Match; Absolute Norm
24,sliding tackle,sliding tackle,numeric,numeric,Exact Match; Absolute Norm
25,short passing,short passing,numeric,numeric,Exact Match; Absolute Norm
26,shot power,shot power,numeric,numeric,Exact Match; Absolute Norm
27,curve,curve,numeric,numeric,Exact Match; Absolute Norm
28,dri,dri,numeric,numeric,Exact Match; Absolute Norm
29,jumping,jumping,numeric,numeric,Exact Match; Absolute Norm
30,vision,vision,numeric,numeric,Exact Match; Absolute Norm
31,crossing,crossing,numeric,numeric,Exact Match; Absolute Norm
32,finishing,finishing,numeric,numeric,Exact Match; Absolute Norm
33,balance,balance,numeric,numeric,Exact Match; Absolute Norm
34,sho,sho,numeric,numeric,Exact Match; Absolute Norm
35,composure,composure,numeric,numeric,Exact Match; Absolute Norm
36,dribbling,dribbling,numeric,numeric,Exact Match; Absolute Norm
37,stamina,stamina,numeric,numeric,Exact Match; Absolute Norm
38,ID,ID,numeric,numeric,Exact Match; Absolute Norm

Do you want to proceed? (y/n):y

In [148]:
dt = em.DTMatcher(name='DecisionTree', random_state=0)
svm = em.SVMMatcher(name='SVM', random_state=0)
rf = em.RFMatcher(name='RF', random_state=0)
lg = em.LogRegMatcher(name='LogReg', random_state=0)
ln = em.LinRegMatcher(name='LinReg')
nb = em.NBMatcher(name='NaiveBayes')

In [151]:
H = em.extract_feature_vecs(I, 
                            feature_table=match_f, 
                            attrs_after=['gold_labels'])

result = em.select_matcher([dt, rf, svm, ln, lg, nb], table=H, 
        exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'],
        k=5, target_attr='gold_labels', 
        metrics_to_display=['precision', 'recall', 'f1'], random_state=0)

result['cv_stats']

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:02

        Matcher  Average precision  Average recall  Average f1
0  DecisionTree           0.956213        0.968065    0.961591
1            RF           0.986058        0.974126    0.980000
2           SVM           0.937569        0.987879    0.961644
3        LinReg           0.903675        0.974126    0.936521
4        LogReg           0.967675        0.980186    0.973640
5    NaiveBayes           0.992308        0.974126    0.982981

In [152]:
L = em.extract_feature_vecs(J, feature_table=match_f,
                            attrs_after='gold_labels')

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:01

In [158]:
nb.fit(table=H, 
       exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
       target_attr='gold_labels')

predictions = nb.predict(table=L, exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
              append=True, target_attr='predicted', inplace=False)

In [159]:
eval_result = em.eval_matches(predictions, 'gold_labels', 'predicted')
em.print_eval_summary(eval_result)

Precision : 98.36% (60/61)
Recall : 98.36% (60/61)
F1 : 98.36%
False positives : 1 (out of 61 positive predictions)
False negatives : 1 (out of 74 negative predictions)

In [160]:
dt.fit(table=H, 
       exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
       target_attr='gold_labels')

predictions = dt.predict(table=L, exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
              append=True, target_attr='predicted', inplace=False)

eval_result = em.eval_matches(predictions, 'gold_labels', 'predicted')
em.print_eval_summary(eval_result)

Precision : 96.77% (60/62)
Recall : 98.36% (60/61)
F1 : 97.56%
False positives : 2 (out of 62 positive predictions)
False negatives : 1 (out of 73 negative predictions)

In [161]:
svm.fit(table=H, 
       exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
       target_attr='gold_labels')

predictions = svm.predict(table=L, exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
              append=True, target_attr='predicted', inplace=False)

eval_result = em.eval_matches(predictions, 'gold_labels', 'predicted')
em.print_eval_summary(eval_result)

Precision : 93.75% (60/64)
Recall : 98.36% (60/61)
F1 : 96.0%
False positives : 4 (out of 64 positive predictions)
False negatives : 1 (out of 71 negative predictions)

In [162]:
rf.fit(table=H, 
       exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
       target_attr='gold_labels')

predictions = rf.predict(table=L, exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
              append=True, target_attr='predicted', inplace=False)

eval_result = em.eval_matches(predictions, 'gold_labels', 'predicted')
em.print_eval_summary(eval_result)

Precision : 93.75% (60/64)
Recall : 98.36% (60/61)
F1 : 96.0%
False positives : 4 (out of 64 positive predictions)
False negatives : 1 (out of 71 negative predictions)

In [163]:
lg.fit(table=H, 
       exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
       target_attr='gold_labels')

predictions = lg.predict(table=L, exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
              append=True, target_attr='predicted', inplace=False)

eval_result = em.eval_matches(predictions, 'gold_labels', 'predicted')
em.print_eval_summary(eval_result)

Precision : 95.24% (60/63)
Recall : 98.36% (60/61)
F1 : 96.77%
False positives : 3 (out of 63 positive predictions)
False negatives : 1 (out of 72 negative predictions)

In [164]:
ln.fit(table=H, 
       exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
       target_attr='gold_labels')

predictions = ln.predict(table=L, exclude_attrs=['_id', 'ltable_ID', 'rtable_ID', 'gold_labels'], 
              append=True, target_attr='predicted', inplace=False)

eval_result = em.eval_matches(predictions, 'gold_labels', 'predicted')
em.print_eval_summary(eval_result)

Precision : 96.77% (60/62)
Recall : 98.36% (60/61)
F1 : 97.56%
False positives : 2 (out of 62 positive predictions)
False negatives : 1 (out of 73 negative predictions)